With WX 3.1.3 Error Fix
I built with wx 3.1.3 at ubuntu 18.04

But, I see a next errorr message :
/Source/Core/DolphinWX/WxUtils.cpp:158:34: error: call of overloaded ‘wxDisplay(int)’ is ambiguous
     screen_geometry = wxDisplay(0).GetClientArea();

Because wxDisplay function structure:
wxDisplay(unsigned int)

So, I fix to next:
wxDisplay((unsigned int)0);

I can built complete.